### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by pjxiao** [beproud/beproud.django.basemodels#8]
Five years ago, we created this repository in order to split huge beproud/bpcommons into serveral small handy repositories.
But there've bee no progress in this repository since then. On the other hand, beproud/bpcommons has been continuaslly maintained and is still alive.

Is this repository still alive? Or are there anyone who uses this repository? If not, I think it's time to archive this repository.

**Comment by bp-xiao** [comment]
I couldn't find any active repositories which use this package, so we've decided to archive this repository.
